<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <FileVersion>09.09.2026.0</FileVersion>
    <AssemblyVersion>09.09.2026.0</AssemblyVersion>
    <AssemblyTitle>Low Level In-Game Events</AssemblyTitle>
    <Authors>Nozomu-san</Authors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunityScriptHookVDotNetCore\CommunityScriptHookVDotNetCore.csproj" />
    <ProjectReference Include="..\LocalNativeMemories\LocalNativeMemories.csproj" />
  </ItemGroup>

</Project>
