<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Platforms>x64</Platforms>
    <AssemblyTitle>Script4 Reload Tool</AssemblyTitle>
    <Authors>Nozomu-san</Authors>
    <AssemblyVersion>04.10.2026.0</AssemblyVersion>
    <FileVersion>04.10.2026.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Source\AssemblyMetadata.fs" />
    <Compile Include="Source\ReloadConfiguration.fs" />
    <Compile Include="Source\ReloadLog.fs" />
    <Compile Include="Source\Scripts4Watcher.fs" />
    <Compile Include="Source\ReloadLifecycle.fs" />
    <Compile Include="Source\Script4ReloadExtension.fs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CommunityScriptHookVDotNetCore">
      <HintPath>..\CommunityScriptHookVDotNetCore\bin\x64\Release\net11.0\CommunityScriptHookVDotNetCore.dll</HintPath>
    </Reference>
    <Reference Include="ScriptHookInput">
      <HintPath>..\ScriptHookInput\bin\x64\Release\net11.0\ScriptHookInput.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>