<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <Authors>Nozomu-san</Authors>
    <AssemblyTitle>Community Script Hook V .NET Core</AssemblyTitle>
    <AssemblyVersion>09.09.2026.0</AssemblyVersion>
    <FileVersion>09.09.2026.0</FileVersion>
  </PropertyGroup>
</Project>