<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <AssemblyVersion>04.10.2026.0</AssemblyVersion>
    <FileVersion>04.10.2026.0</FileVersion>
    <AssemblyTitle>Standard Game Operations</AssemblyTitle>
    <Authors>Nozomu-san</Authors>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Source\" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Alloc8orStandardNatives">
      <HintPath>..\Alloc8orStandardNatives\bin\x64\Release\net11.0\Alloc8orStandardNatives.dll</HintPath>
    </Reference>
    <Reference Include="CommunityScriptHookVDotNetCore">
      <HintPath>..\CommunityScriptHookVDotNetCore\bin\x64\Release\net11.0\CommunityScriptHookVDotNetCore.dll</HintPath>
    </Reference>
    <Reference Include="LocalNativeMemories">
      <HintPath>..\LocalNativeMemories\bin\x64\Release\net11.0\LocalNativeMemories.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>