<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <AssemblyTitle>Alloc8or's Standard Native Executables</AssemblyTitle>
    <Authors>Nozomu-san</Authors>
    <AssemblyVersion>09.09.2026.0</AssemblyVersion>
    <FileVersion>09.09.2026.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CommunityScriptHookVDotNetCore\CommunityScriptHookVDotNetCore.csproj" />
  </ItemGroup>
</Project>